//go:build ignore

// This file is ONLY used by `go generate`. It imports sprig to extract
// all registered function names and writes them to sprig_stubs.go.
// The production binary does NOT depend on sprig at all.
//
//   go generate ./...

package main

import (
	"fmt"
	"os"
	"sort"

	"github.com/Masterminds/sprig/v3"
)

func main() {
	f := sprig.TxtFuncMap()
	delete(f, "env")       // Helm removes these
	delete(f, "expandenv")

	keys := make([]string, 0, len(f))
	for k := range f {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	out, err := os.Create("sprig_stubs.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error creating sprig_stubs.go: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by go generate -- DO NOT EDIT")
	fmt.Fprintln(out, "// Regenerate with: go generate ./...")
	fmt.Fprintln(out, "package main")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "// sprigStubNames contains every function name registered by sprig")
	fmt.Fprintln(out, "// (minus env/expandenv which Helm drops). One no-op stub is registered")
	fmt.Fprintln(out, "// under each name so that template.Parse succeeds at validation time.")
	fmt.Fprintln(out, "var sprigStubNames = []string{")
	for _, k := range keys {
		fmt.Fprintf(out, "	%q,\n", k)
	}
	fmt.Fprintln(out, "}")
}
